// client-angular/src/app/features/opinly/pages/opinly/opinly.ts
import { Component } from '@angular/core';
import { OpinlyHeader } from "../../components/opinly-header/opinly-header";
import { NewOpinion } from "../../components/new-opinion/new-opinion";
import { OpinionsList } from "../../components/opinions-list/opinions-list";

@Component({
  selector: 'app-opinly',
  imports: [OpinlyHeader, NewOpinion, OpinionsList],
  templateUrl: './opinly.html',
  styleUrl: './opinly.css',
})
export class Opinly {

}

// client/src/pages/Opinly/Opinly.tsx
import Div from "@/components/Html/Div/Div"
import NewOpinion from "@/components/Systems/Opinly/NewOpinion/NewOpinion"
import Opinions from "@/components/Systems/Opinly/Opinions/Opinions"
import Header from "@/components/Systems/Opinly/partials/Header/Header"
import classes from "./Opinly.module.css"

const Opinly: React.FC = () => {

    return (
        <Div>
            <Header />
            <main className={classes.main}>
                <NewOpinion />
                <Opinions />
            </main>
        </Div>
    )

}

export default Opinly
