// client-angular/src/app/features/auth/pages/login/login.component.ts
import { Component, signal } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { RouterLink, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../../core/services/auth/auth.service';
import { ToastService } from '../../../../shared/services/toast.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule, RouterLink],
  template: `
    <div class="min-h-screen px-6 sm:px-0 pt-24 pb-10 bg-gradient-to-br from-blue-200 to-purple-400 flex items-center justify-center text-indigo-300">
      <div class="bg-slate-900 p-10 rounded-lg shadow-lg w-full sm:w-96 text-sm border border-slate-700">
          <h2 class="text-3xl font-semibold text-white text-center mb-3">Login</h2>
          <p class="text-center text-sm mb-6 text-indigo-200">Logue na sua conta</p>

          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
            <div class="mb-4 flex items-center gap-3 w-full px-5 py-2.5 rounded-full bg-[#333A5C]">
              <img src="/assets/svg/mail.svg" alt="Email" class="w-5 h-5" />
              <input
                id="email"
                type="email"
                formControlName="email"
                class="bg-transparent outline-none flex-1 text-sm placeholder-indigo-200/70"
                placeholder="E-mail"
                required
              />
            </div>
            @if (loginForm.get('email')?.invalid && loginForm.get('email')?.touched) {
              <span class="text-xs text-red-400 mb-2 block">Email é obrigatório</span>
            }

            <div class="mb-4 flex items-center gap-3 w-full px-5 py-2.5 rounded-full bg-[#333A5C]">
              <img src="/assets/svg/lock.svg" alt="Senha" class="w-5 h-5" />
              <input
                id="password"
                type="password"
                formControlName="password"
                class="bg-transparent outline-none flex-1 text-sm placeholder-indigo-200/70"
                placeholder="Senha"
                required
              />
            </div>
            @if (loginForm.get('password')?.invalid && loginForm.get('password')?.touched) {
              <span class="text-xs text-red-400 mb-2 block">Senha é obrigatória</span>
            }

            <p
              class="mb-4 text-indigo-500 cursor-pointer text-xs text-right hover:underline"
              (click)="goToResetPassword()"
            >
              Esqueceu sua senha?
            </p>

            <button
              type="submit"
              class="w-full py-2.5 rounded-full bg-gradient-to-r from-indigo-500 to-indigo-900 text-white font-medium disabled:opacity-60 disabled:cursor-not-allowed"
              [disabled]="loginForm.invalid || loading()"
            >
              @if (loading()) {
                Carregando...
              } @else {
                Login
              }
            </button>
          </form>

          <p class="text-gray-400 text-center text-xs mt-4">
            Não tem uma conta?
            <a routerLink="/signup" class="text-blue-400 cursor-pointer hover:underline">Cadastre-se</a>
          </p>
      </div>
    </div>
  `,
  styles: []
})
export class LoginComponent {
  loginForm: FormGroup;
  loading = signal(false);

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private toast: ToastService
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]]
    });
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      this.loading.set(true);
      const { email, password } = this.loginForm.value;

      this.authService.login({ email, password }).subscribe({
        next: (response) => {
          if (response.success) {
            this.toast.success(response.message || 'Login realizado com sucesso!');
            this.router.navigate(['/systems']);
          } else {
            this.toast.error(response.message || 'Erro ao fazer login');
          }
          this.loading.set(false);
        },
        error: () => {
          this.toast.error('Erro ao fazer login. Tente novamente.');
          this.loading.set(false);
        }
      });
    }
  }

  goToResetPassword(): void {
    this.router.navigate(['/reset-password']);
  }
}

// client/src/pages/Auth/Login.tsx
import { useContext } from "react";
import { useNavigate } from "react-router-dom";

import useGetBackendUrl from "../../hooks/backend/useGetBackendUrl";
import useLoginOrSignup from "../../hooks/states/useLoginOrSignup";

import { loginUser } from "../../api/login";

import { AppContext } from "../../context/AppContext";

import { toast } from "react-toastify";

import mail from "../../assets/svg/mail.svg"
import lock from "../../assets/svg/lock.svg"

import Div from "../../components/Html/Div/Div";
import DivLoginSignUp from "../../components/DivLoginSignUp/DivLoginSignUp";
import Header2 from "../../components/Html/Header2/Header2";
import Paragraph from "../../components/Html/Paragraph/Paragraph";
import Image from "../../components/Html/Image/Image";
import Button from "../../components/Html/Button/Button";
import Navbar from "../../components/Navbar/Navbar";

const Login: React.FC = () => {

    const navigate = useNavigate()

    const { backendUrl } = useGetBackendUrl()

    const { email, setEmail, password, setPassword } = useLoginOrSignup("login")

    const context = useContext(AppContext)

    if (!context) {
        throw new Error("AppContext não foi provido")
    }

    const { setIsLoggedIn, getUserData } = context

    const onSubmitHandler = async (e: React.FormEvent<HTMLFormElement>) => {
        try {
            e.preventDefault()

            const data = await loginUser(backendUrl, { email, password })

            if (data.success) {
                toast.success('Usuário logado com sucesso!')
                setIsLoggedIn(true)
                getUserData()
                navigate('/')
            } else {
                toast.error(data.message)
            }
        } catch (error: any) {
            toast.error(error.message)
        }
    }

    return (
        <Div>
            <Navbar />
            <DivLoginSignUp>
                <Div className="bg-slate-900 p-10 rounded-lg shadow-lg w-full sm:w-96 text-indigo-300 text-sm">
                    <Header2 className="text-3xl font-semibold text-white text-center mb-3" text="Login" />
                    <Paragraph className="text-center text-sm mb-6" text="Logue na sua conta" />

                    <form onSubmit={onSubmitHandler}>
                        <Div className="mb-4 flex items-center gap-3 w-full px-5 py-2.5 rounded-full bg-[#333A5C]">
                            <Image src={mail} alt="Email" />
                            <input onChange={e => setEmail(e.target.value)} value={email} className="bg-transparent outline-none" type="email" placeholder="E-mail" required />
                        </Div>

                        <Div className="mb-4 flex items-center gap-3 w-full px-5 py-2.5 rounded-full bg-[#333A5C]">
                            <Image src={lock} alt="Senha" />
                            <input onChange={e => setPassword(e.target.value)} value={password} className="bg-transparent outline-none" type="password" placeholder="Senha" required />
                        </Div>

                        <p onClick={() => navigate('/reset-password')} className="mb-4 text-indigo-500 cursor-pointer">Esqueceu sua senha?</p>

                        <Button className="w-full py-2.5 rounded-full bg-gradient-to-r from-indigo-500 to-indigo-900 text-white font-medium" text="Login" />
                    </form>

                    <Paragraph className="text-gray-400 text-center text-xs mt-4" text="Não tem uma conta?" />
                    <span onClick={() => navigate('/signup')} className="text-blue-400 cursor-pointer"> Cadastre-se</span>
                </Div>
            </DivLoginSignUp>
        </Div>
    )

}

export default Login
