// client-angular/src/app/features/auth/pages/signup/signup.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../../core/services/auth/auth.service';
import { ToastService } from '../../../../shared/services/toast.service';
import { AUTH_MESSAGES } from '../../../../core/constants/auth-messages';
import { getApiErrorMessage } from '../../../../core/utils/api-error.util';
import { I18nService } from '../../../../core/services/i18n/i18n.service';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule, RouterLink],
  template: `
    <div class="flex min-h-screen items-center justify-center bg-gradient-to-br from-blue-200 to-purple-400 px-6 sm:px-0">
      <div class="w-full rounded-lg bg-slate-900 p-10 text-sm text-indigo-300 shadow-lg sm:w-96">
        <h2 class="mb-3 text-center text-3xl font-semibold text-white">{{ i18n.t('auth.signup') }}</h2>
        <p class="mb-6 text-center text-sm">{{ i18n.t('auth.signupSubtitle') }}</p>

        <form [formGroup]="signupForm" (ngSubmit)="onSubmit()">
          <div class="mb-4 flex w-full items-center gap-3 rounded-full bg-[#333A5C] px-5 py-2.5">
            <img src="/assets/svg/person.svg" [alt]="i18n.t('common.iconAlt')" class="h-5 w-5" />
            <input
              id="name"
              type="text"
              formControlName="name"
              class="flex-1 bg-transparent text-sm outline-none"
              [placeholder]="i18n.t('auth.fullName')"
              required
            />
          </div>

          <div class="mb-4 flex w-full items-center gap-3 rounded-full bg-[#333A5C] px-5 py-2.5">
            <img src="/assets/svg/mail.svg" [alt]="i18n.t('auth.email')" class="h-5 w-5" />
            <input
              id="email"
              type="email"
              formControlName="email"
              class="flex-1 bg-transparent text-sm outline-none"
              [placeholder]="i18n.t('auth.email')"
              required
            />
          </div>

          <div class="mb-4 flex w-full items-center gap-3 rounded-full bg-[#333A5C] px-5 py-2.5">
            <img src="/assets/svg/lock.svg" [alt]="i18n.t('auth.password')" class="h-5 w-5" />
            <input
              id="password"
              type="password"
              formControlName="password"
              class="flex-1 bg-transparent text-sm outline-none"
              [placeholder]="i18n.t('auth.password')"
              required
            />
          </div>

          <p
            class="mb-4 cursor-pointer text-indigo-500"
            (click)="goToResetPassword()"
          >
            {{ i18n.t('auth.forgotPassword') }}
          </p>

          <button
            type="submit"
            class="w-full rounded-full bg-gradient-to-r from-indigo-500 to-indigo-900 py-2.5 font-medium text-white disabled:cursor-not-allowed disabled:opacity-60"
            [disabled]="signupForm.invalid || loading()"
          >
            @if (loading()) {
              {{ i18n.t('common.loading') }}
            } @else {
              {{ i18n.t('auth.register') }}
            }
          </button>
        </form>

        <p class="mt-4 text-center text-xs text-gray-400">
          {{ i18n.t('auth.alreadyHaveAccount') }}
          <a routerLink="/login" class="cursor-pointer text-blue-400">{{ i18n.t('auth.login') }}</a>
        </p>
      </div>
    </div>
  `,
  styles: [],
})
export class SignupComponent {
  readonly i18n = inject(I18nService);
  signupForm: FormGroup;
  loading = signal(false);

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private toast: ToastService
  ) {
    this.signupForm = this.fb.group({
      name: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
    });
  }

  onSubmit(): void {
    if (this.signupForm.valid) {
      this.loading.set(true);
      const { name, email, password } = this.signupForm.value;

      this.authService.register({ name, email, password }).subscribe({
        next: (response) => {
          if (response.success) {
            this.toast.success(AUTH_MESSAGES.signupSuccess);
            this.router.navigate(['/']);
          } else {
            this.toast.error(response.message || 'Erro ao cadastrar');
          }
          this.loading.set(false);
        },
        error: (err) => {
          this.toast.error(getApiErrorMessage(err, 'Erro ao cadastrar. Tente novamente.'));
          this.loading.set(false);
        },
      });
    }
  }

  goToResetPassword(): void {
    this.router.navigate(['/reset-password']);
  }
}

// client/src/pages/Auth/Signup.tsx
import { useContext } from "react";
import { useTranslation } from "react-i18next";
import { AppContext } from "@/context/AppContext";
import useGetBackendUrl from "@/hooks/backend/useGetBackendUrl";
import useNavigateSPA from "@/hooks/routes/useNavigateSPA";
import useLoginOrSignup from "@/hooks/states/useLoginOrSignup";
import { toast } from "react-toastify";
import i18n from "@/i18n";
import { registerUser } from "@/api/register";
import person from "@/assets/svg/person.svg"
import mail from "@/assets/svg/mail.svg"
import lock from "@/assets/svg/lock.svg"
import DivLoginSignUp from "@/components/DivLoginSignUp/DivLoginSignUp";
import Div from "@/components/Html/Div/Div";
import Header2 from "@/components/Html/Header2/Header2";
import Paragraph from "@/components/Html/Paragraph/Paragraph";
import Image from "@/components/Html/Image/Image";
import Button from "@/components/Html/Button/Button";
import Navbar from "@/components/Navbar/Navbar";

const Signup: React.FC = () => {

    const navigate = useNavigateSPA()
    const { t } = useTranslation()

    const { backendUrl } = useGetBackendUrl()

    const { name, setName, email, setEmail, password, setPassword } = useLoginOrSignup("signup")

    const context = useContext(AppContext)

    if (!context) {
        throw new Error(t('auth.appContextError'))
    }

    const { setIsLoggedIn, getUserData } = context

    const onSubmitHandler = async (e: React.FormEvent<HTMLFormElement>) => {
        try {
            e.preventDefault()

            if (!name) {
                toast.error(t('auth.nameRequired'))
                return
            }

            const data = await registerUser(backendUrl, { name, email, password })

            if (data.success) {
                toast.success(i18n.t('auth.signupSuccess'))
                setIsLoggedIn(true)
                getUserData()
                setTimeout(() => navigate('/'), 150)
            } else {
                toast.error(data.message)
            }
        } catch (error: any) {
            toast.error(error.message)
        }
    }

    return (
        <Div>
            <Navbar />
            <DivLoginSignUp>
                <Div className="bg-slate-900 p-10 rounded-lg shadow-lg w-full sm:w-96 text-indigo-300 text-sm">
                    <Header2 className="text-3xl font-semibold text-white text-center mb-3" text={t('auth.signup')} />

                    <Paragraph className="text-center text-sm mb-6" text={t('auth.signupSubtitle')} />

                    <form onSubmit={onSubmitHandler}>
                        <Div className="mb-4 flex items-center gap-3 w-full px-5 py-2.5 rounded-full bg-[#333A5C]">
                            <Image src={person} alt={t('common.iconAlt')} />
                            <input onChange={e => setName!(e.target.value)} value={name} className="bg-transparent outline-none" type="text" placeholder={t('auth.fullName')} required />
                        </Div>

                        <Div className="mb-4 flex items-center gap-3 w-full px-5 py-2.5 rounded-full bg-[#333A5C]">
                            <Image src={mail} alt={t('auth.email')} />
                            <input onChange={e => setEmail(e.target.value)} value={email} className="bg-transparent outline-none" type="email" placeholder={t('auth.email')} required />
                        </Div>

                        <Div className="mb-4 flex items-center gap-3 w-full px-5 py-2.5 rounded-full bg-[#333A5C]">
                            <Image src={lock} alt={t('auth.password')} />
                            <input onChange={e => setPassword(e.target.value)} value={password} className="bg-transparent outline-none" type="password" placeholder={t('auth.password')} required />
                        </Div>

                        <p onClick={() => navigate('/reset-password')} className="mb-4 text-indigo-500 cursor-pointer">{t('auth.forgotPassword')}</p>

                        <Button className="w-full py-2.5 rounded-full bg-gradient-to-r from-indigo-500 to-indigo-900 text-white font-medium" text={t('auth.register')} />
                    </form>

                    <p className='text-gray-400 text-center text-xs mt-4'>{t('auth.alreadyHaveAccount')}
                        <span onClick={() => navigate('/login')} className='text-blue-400 cursor-pointer'> {t('auth.login')}</span>
                    </p>
                </Div>
            </DivLoginSignUp>
        </Div>
    )

}

export default Signup
