// client/src/components/Systems/Opinly/NewOpinion/NewOpinion.tsx
import { useActionState, useContext } from "react";
import { useTranslation } from "react-i18next";
import i18n from "../../../../i18n";
import { OpinionsContext } from "../../../../context/Opinly/OpinlyContext";
import Submit from "../partials/Submit";
import Div from "../../../Html/Div/Div";
import classes from "./NewOpinion.module.css"
import type { IFormState } from "../../../../interfaces/systems/opinly";

const NewOpinion: React.FC = () => {
    const { t } = useTranslation()

    const opinionsContext = useContext(OpinionsContext);

    if (!opinionsContext) {
        return null
    }

    const { addOpinion } = opinionsContext;

    async function shareOpinionsAction(prevState: IFormState, formData: FormData) {
        const title = String(formData.get('title') ?? '');
        const body = String(formData.get('body') ?? '');
        const userName = formData.get('userName')

        let errors = []

        if (title.trim().length < 5) {
            errors.push(i18n.t('opinly.titleMinLength'))
        }

        if (body.trim().length < 10 || body.trim().length > 300) {
            errors.push(i18n.t('opinly.bodyLength'))
        }

        if (typeof userName !== "string" || !userName.trim()) {
            errors.push(i18n.t('opinly.nameRequired'))
        }

        if (errors.length > 0) {
            return {
                errors, enteredValues: {
                    title, body, userName
                }
            }
        }
        await addOpinion({
            id: "", 
            title,
            body,
            userName: String(userName ?? ''),
            votes: 0 
        });

        return { errors: null }
    }

    const [formState, formAction] = useActionState(
        shareOpinionsAction as (
            state: any,
            formData: FormData
        ) => Promise<any> | any, 
        {
            errors: null
        }
    );

    return (
        <Div className={classes['new-opinion']}>
            <form action={formAction} className={classes.form}>
                <Div className={classes['control-row']}>
                    <p className={classes.control}>
                        <label htmlFor="userName">{t('opinly.yourName')}</label>
                        <input
                            type="text"
                            id="userName"
                            name="userName"
                            defaultValue={
                                formState?.enteredValues?.userName != null
                                    ? String(formState.enteredValues.userName)
                                    : undefined
                            }
                        />
                    </p>
                    <p className={classes.control}>
                        <label htmlFor="title">{t('opinly.titleLabel')}</label>
                        <input type="text" id="title" name="title"
                            defaultValue={formState?.enteredValues?.title}
                        />
                    </p>
                </Div>
                <p className={`${classes.control} ${classes.top}`}>
                    <label htmlFor="body">{t('opinly.yourOpinion')}</label>
                    <textarea name="body" id="body" rows={5}
                        defaultValue={formState?.enteredValues?.body}
                    ></textarea>
                </p>
                {formState?.errors && (
                    <ul className={classes.errors}>
                        {formState?.errors.map((error: any) => (
                            <li key={error}>{error}</li>
                        ))}
                    </ul>
                )}
                <Submit />
            </form>
        </Div>
    )

}

export default NewOpinion

// client-angular/src/app/features/opinly/components/new-opinion/new-opinion.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { I18nService } from '../../../../core/services/i18n/i18n.service';
import { OpinlyStateService } from '../../../../core/services/state/opinly-state.service';

@Component({
  selector: 'app-new-opinion',
  imports: [FormsModule],
  templateUrl: './new-opinion.html',
  styleUrl: './new-opinion.css',
})
export class NewOpinion {
  private readonly opinlyState = inject(OpinlyStateService);
  readonly i18n = inject(I18nService);

  userName = '';
  title = '';
  body = '';
  errors = signal<string[]>([]);
  submitting = signal(false);

  submit(): void {
    const errors: string[] = [];
    if (this.title.trim().length < 5) errors.push(this.i18n.t('opinly.titleMinLength'));
    if (this.body.trim().length < 10 || this.body.trim().length > 300) errors.push(this.i18n.t('opinly.bodyLength'));
    if (!this.userName.trim()) errors.push(this.i18n.t('opinly.nameRequired'));

    this.errors.set(errors);
    if (errors.length) return;

    this.submitting.set(true);
    this.opinlyState
      .addOpinion({
        id: '',
        title: this.title.trim(),
        body: this.body.trim(),
        userName: this.userName.trim(),
        votes: 0
      })
      .subscribe({
        next: () => {
          this.userName = '';
          this.title = '';
          this.body = '';
          this.errors.set([]);
          this.submitting.set(false);
        },
        error: () => {
          this.submitting.set(false);
        }
      });
  }
}
