// client/src/pages/Talkive/Sections/Login/Login.tsx
import { useState, useContext } from 'react'
import { useTranslation } from 'react-i18next'
import { signup, login, resetPass } from '@/api/talkive/config/firebase'
import { TalkiveContext } from '@/context/Talkive/TalkiveContext'
import './Login.sass'

type ICurrentState = 'Cadastrar-se' | 'Login'

const LoginTalkive: React.FC = () => {
    const { t } = useTranslation()
    const [currentState, setCurrentState] = useState<ICurrentState>('Cadastrar-se')
    const [userName, setUserName] = useState('')
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')

    const talkiveContext = useContext(TalkiveContext)
    const setChatUser = talkiveContext?.setChatUser

    const onSubmitHandler = (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault()

        if (currentState === 'Cadastrar-se'){
            signup({username: userName, email, password})
            setChatUser && setChatUser(null)
        } else {
            login({email, password})
            setChatUser && setChatUser(null)
        }
    }

    return (
        <div className='login'>
            <form onSubmit={onSubmitHandler} className='login-form'>
                {currentState === 'Cadastrar-se' ? <input onChange={(e) => setUserName(e.target.value)} value={userName} required type='text' placeholder={t('talkive.signup.name')} className='form-input' /> : null}
                <input onChange={(e) => setEmail(e.target.value)} value={email} required type='email' placeholder={t('talkive.login.email')} className='form-input' />
                <input onChange={(e) => setPassword(e.target.value)} value={password} required type='password' placeholder={t('talkive.login.password')} className='form-input' />
                <button type='submit'>{currentState === 'Cadastrar-se' ? t('talkive.signup.createAccount') : t('talkive.login.title')}</button>
                <div className='login-term'>
                    <input type='checkbox' />
                    <p>{t('talkive.signup.agree')}</p>
                </div>
                <div className='login-forgot'>
                    {
                        currentState === 'Cadastrar-se' ? 
                        <p className='login-toggle'>
                            {t('talkive.signup.alreadyHaveAccount')} <span onClick={() => setCurrentState('Login')}>{t('talkive.signup.alreadyHaveAccountLink')}</span>
                        </p>
                        : 
                        <p className='login-toggle'>
                            {t('talkive.login.createAccount')} <span onClick={() => setCurrentState('Cadastrar-se')}>{t('talkive.login.createAccountLink')}</span>
                        </p>
                    }
                    {
                        currentState === 'Login' ?
                        <p className='login-toggle'>
                            {t('talkive.login.forgotPassword')} <span onClick={() => resetPass({email})}>{t('talkive.login.resetPassword')}</span>
                        </p> :
                        null
                    }
                </div>
            </form>
        </div>
    )
}

export default LoginTalkive

// client-angular/src/app/features/talkive/pages/login/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { I18nService } from '@/app/core/services/i18n/i18n.service';
import { TalkiveService } from '@/app/core/services/talkive/talkive.service';
import { ToastService } from '@/app/shared/services/toast.service';

@Component({
  selector: 'app-talkive-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class TalkiveLoginComponent {
  private readonly talkiveService = inject(TalkiveService);
  private readonly toastService = inject(ToastService);
  readonly i18n = inject(I18nService);

  mode = signal<'signup' | 'login'>('signup');
  username = '';
  email = '';
  password = '';

  async submit(): Promise<void> {
    if (!this.email || !this.password) return;
    if (this.mode() === 'signup' && !this.username) return;

    try {
      if (this.mode() === 'signup') {
        await this.talkiveService.signup({ username: this.username, email: this.email, password: this.password });
        this.toastService.success(this.i18n.t('talkive.signup.createAccount'));
      } else {
        await this.talkiveService.login({ email: this.email, password: this.password });
        this.toastService.success(this.i18n.t('auth.loginSuccess'));
      }
    } catch (error: unknown) {
      const err = error as { code?: string; message?: string };
      const message = err?.code?.split('/')[1]?.split('-').join(' ') || err?.message || this.i18n.t('talkive.errors.createProfile');
      this.toastService.error(message);
    }
  }

  async forgotPassword(): Promise<void> {
    if (!this.email) {
      this.toastService.warning(this.i18n.t('auth.insertEmailError'));
      return;
    }

    const sent = await this.talkiveService.resetPassword({ email: this.email });
    if (sent) {
      this.toastService.success(this.i18n.t('talkive.errors.emailSent'));
    } else {
      this.toastService.error(this.i18n.t('talkive.errors.emailNotExist'));
    }
  }
}

<div class="login">
  <form (ngSubmit)="submit()" class="login-form">
    @if (mode() === 'signup') {
      <input
        [(ngModel)]="username"
        name="username"
        required
        type="text"
        [placeholder]="i18n.t('talkive.signup.name')"
        class="form-input"
      />
    }
    <input
      [(ngModel)]="email"
      name="email"
      required
      type="email"
      [placeholder]="i18n.t('talkive.login.email')"
      class="form-input"
    />
    <input
      [(ngModel)]="password"
      name="password"
      required
      type="password"
      [placeholder]="i18n.t('talkive.login.password')"
      class="form-input"
    />
    <button type="submit">
      {{ mode() === 'signup' ? i18n.t('talkive.signup.createAccount') : i18n.t('talkive.login.title') }}
    </button>

    <div class="login-term">
      <input type="checkbox" />
      <p>{{ i18n.t('talkive.login.agree') }}</p>
    </div>

    <div class="login-forgot">
      @if (mode() === 'signup') {
        <p class="login-toggle">
          {{ i18n.t('talkive.signup.alreadyHaveAccount') }}
          <span (click)="mode.set('login')">{{ i18n.t('talkive.signup.alreadyHaveAccountLink') }}</span>
        </p>
      } @else {
        <p class="login-toggle">
          {{ i18n.t('talkive.login.createAccount') }}
          <span (click)="mode.set('signup')">{{ i18n.t('talkive.login.createAccountLink') }}</span>
        </p>
        <p class="login-toggle">
          {{ i18n.t('talkive.login.forgotPassword') }}
          <span (click)="forgotPassword()">{{ i18n.t('talkive.login.resetPassword') }}</span>
        </p>
      }
    </div>
  </form>
</div>
