// client-angular/src/app/features/talkive/components/chat-box/chat-box.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { TALKIVE_ASSETS } from '@/assets/talkive/ts/assets';
import { formatTalkiveTimestamp } from '@/app/core/utils/talkive/timestamp.util';
import { IMessage } from '@/app/core/models/systems/talkive/talkive.model';
import { CloudinaryService } from '@/app/core/services/cloudinary/cloudinary.service';
import { I18nService } from '@/app/core/services/i18n/i18n.service';
import { TalkiveStateService } from '@/app/core/services/state/talkive-state.service';
import { TalkiveService } from '@/app/core/services/talkive/talkive.service';
import { ToastService } from '@/app/shared/services/toast.service';

@Component({
  selector: 'app-talkive-chat-box',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './chat-box.component.html',
})
export class TalkiveChatBoxComponent {
  readonly assets = TALKIVE_ASSETS;
  readonly talkiveState = inject(TalkiveStateService);
  private readonly talkiveService = inject(TalkiveService);
  private readonly cloudinary = inject(CloudinaryService);
  private readonly toastService = inject(ToastService);
  readonly i18n = inject(I18nService);

  draft = signal('');

  isOnline(lastSeen: number): boolean {
    return Date.now() - lastSeen <= 70000;
  }

  formatTimestamp(message: IMessage): string {
    return formatTalkiveTimestamp(message.createdAt);
  }

  async sendMessage(): Promise<void> {
    const text = this.draft().trim();
    const user = this.talkiveState.userData();
    const chatUser = this.talkiveState.chatUser();
    const messagesId = this.talkiveState.messagesId();

    if (!text || !user || !chatUser || !messagesId) return;

    try {
      await this.talkiveService.sendMessage(messagesId, user.id, chatUser.id, text);
      this.draft.set('');
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : this.i18n.t('talkive.errors.createProfile');
      this.toastService.error(message);
    }
  }

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      event.preventDefault();
      this.sendMessage();
    }
  }

  async onImageSelected(event: Event): Promise<void> {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    const user = this.talkiveState.userData();
    const chatUser = this.talkiveState.chatUser();
    const messagesId = this.talkiveState.messagesId();

    if (!file || !user || !chatUser || !messagesId) return;

    try {
      const imageUrl = await firstValueFrom(this.cloudinary.upload(file));
      await this.talkiveService.sendImageMessage(messagesId, user.id, chatUser.id, imageUrl);
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : this.i18n.t('talkive.errors.createProfile');
      this.toastService.error(message);
    } finally {
      input.value = '';
    }
  }

  closeChat(): void {
    this.talkiveState.setChatVisible(false);
  }
}

@if (talkiveState.chatUser(); as chatUser) {
  @if (talkiveState.userData(); as userData) {
    <div class="chat-box">
      <div class="chat-user">
        <img [src]="chatUser.avatar || assets.avatar_icon" [alt]="i18n.t('talkive.chat.userAlt')" />
        <p>
          {{ chatUser.name }}
          @if (isOnline(chatUser.lastSeen)) {
            <img [src]="assets.green_dot" alt="" class="dot" />
          }
        </p>
        <img [src]="assets.help_icon" class="help" [alt]="i18n.t('talkive.chat.help')" />
        <img [src]="assets.arrow_icon" class="arrow" [alt]="i18n.t('talkive.chat.arrow')" (click)="closeChat()" />
      </div>

      <div class="chat-msg">
        @for (msg of talkiveState.messages(); track $index) {
          <div [class]="msg.sId === userData.id ? 's-msg' : 'r-msg'">
            @if (msg.image) {
              <img class="msg-img" [src]="msg.image" [alt]="i18n.t('talkive.chat.imageAlt')" />
            } @else {
              <p class="msg">{{ msg.text }}</p>
            }
            <div>
              <img
                [src]="msg.sId === userData.id ? userData.avatar : chatUser.avatar"
                [alt]="i18n.t('talkive.chat.imageAlt')"
              />
              <p>{{ formatTimestamp(msg) }}</p>
            </div>
          </div>
        }
      </div>

      <div class="chat-input">
        <input
          type="text"
          [placeholder]="i18n.t('talkive.chat.sendMessagePlaceholder')"
          [ngModel]="draft()"
          (ngModelChange)="draft.set($event)"
          (keydown)="onKeyDown($event)"
        />
        <input
          type="file"
          id="talkive-image"
          accept="image/png, image/jpeg"
          hidden
          (change)="onImageSelected($event)"
        />
        <label for="talkive-image">
          <img [src]="assets.gallery_icon" [alt]="i18n.t('talkive.chat.gallery')" />
        </label>
        <img [src]="assets.send_button" [alt]="i18n.t('talkive.chat.send')" (click)="sendMessage()" />
      </div>
    </div>
  }
} @else {
  <div class="chat-welcome">
    <img [src]="assets.logo_icon" alt="Logo" />
    <p>{{ i18n.t('talkive.chat.welcomeMessage') }}</p>
  </div>
}

// client/src/components/Systems/Talkive/ChatBox/ChatBox.tsx
import { useContext, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import assets from "@/assets/talkive/ts/assets";
import { TalkiveContext } from "@/context/Talkive/TalkiveContext";
import { onSnapshot, doc, updateDoc, arrayUnion, getDoc, Timestamp } from "firebase/firestore";
import { db } from "@/api/talkive/config/firebase";
import { toast } from "react-toastify";
import upload from "@/api/talkive/lib/upload";
import type { IMessage } from "@/context/Talkive/interfaces";
import './ChatBox.sass'

const ChatBox: React.FC = () => {
    const { t } = useTranslation()
    const talkiveContext = useContext(TalkiveContext)
    const userData = talkiveContext?.userData;
    const messagesId = talkiveContext?.messagesId;
    const chatUser = talkiveContext?.chatUser;
    const messages = talkiveContext?.messages;
    const setMessages = talkiveContext?.setMessages;
    const chatVisible = talkiveContext?.chatVisible;
    const setChatVisible = talkiveContext?.setChatVisible;

    const [input, setInput] = useState("")

    const sendMessage = async () => {
        try {
            if (input && messagesId && userData && chatUser) {
                await updateDoc(doc(db, 'messages', messagesId), {
                    messages: arrayUnion({
                        sId: userData.id,
                        text: input,
                        createdAt: new Date()
                    })
                })

                const userIDs = [chatUser.id, userData.id]

                userIDs.forEach(async (id) => {
                    const userChatsRef = doc(db, 'chats', id)
                    const userChatsSnapshot = await getDoc(userChatsRef)

                    if (userChatsSnapshot.exists()) {
                        const userChatData = userChatsSnapshot.data()
                        const chatIndex = userChatData.chatsData.findIndex((c: any) => c.messageId === messagesId)
                        if (chatIndex !== -1) {
                            userChatData.chatsData[chatIndex].lastMessage = input.slice(0, 30)
                            userChatData.chatsData[chatIndex].updateAt = Date.now()

                            if (userChatData.chatsData[chatIndex].rId === userData.id) {
                                userChatData.chatsData[chatIndex].messageSeen = false
                            }

                            await updateDoc(userChatsRef, {
                                chatsData: userChatData.chatsData
                            })
                        }
                    }
                })
            }
        } catch (error: any) {
            toast.error(error.message)
        }

        setInput('')
    }

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter') {
            sendMessage();
        }
    };

    const sendImage = async (e: React.ChangeEvent<HTMLInputElement>) => {
        try {
            if (!e.target.files || !e.target.files[0] || !userData || !chatUser) {
                return;
            }

            const fileUrl = await upload(e.target.files[0])

            if (fileUrl && messagesId) {
                await updateDoc(doc(db, 'messages', messagesId), {
                    messages: arrayUnion({
                        sId: userData.id,
                        image: fileUrl,
                        createdAt: new Date()
                    })
                })
            }

            const userIDs = [chatUser.id, userData.id]

            userIDs.forEach(async (id) => {
                const userChatsRef = doc(db, 'chats', id)
                const userChatsSnapshot = await getDoc(userChatsRef)

                if (userChatsSnapshot.exists()) {
                    const userChatData = userChatsSnapshot.data()
                    const chatIndex = userChatData.chatsData.findIndex((c: any) => c.messageId === messagesId)
                    if (chatIndex !== -1) {
                        userChatData.chatsData[chatIndex].lastMessage = t('talkive.chat.lastMessageImage')
                        userChatData.chatsData[chatIndex].updateAt = Date.now()

                        if (userChatData.chatsData[chatIndex].rId === userData.id) {
                            userChatData.chatsData[chatIndex].messageSeen = false
                        }

                        await updateDoc(userChatsRef, {
                            chatsData: userChatData.chatsData
                        })
                    }
                }
            })
        } catch (error: any) {
            toast.error(error.message)
        }
    }

    const convertTimestamp = (timestamp: Timestamp | Date) => {
        let date: Date;
        if (timestamp instanceof Date) {
            date = timestamp;
        } else {
            date = timestamp.toDate();
        }

        const hour = date.getHours();
        const minute = date.getMinutes();
        const displayMinute = minute.toString().padStart(2, '0');

        const day = date.getDate();
        const month = date.getMonth() + 1;

        return `(${day}/${month}) ${hour}:${displayMinute}`;
    }

    useEffect(() => {
        if (messagesId && setMessages) {
            setMessages([])
            
            const unSub = onSnapshot(doc(db, 'messages', messagesId), (res) => {
                const data = res.data();
                if (data && data.messages) {
                    setMessages((data.messages as IMessage[]).reverse())
                }
            })

            return () => {
                unSub()
            }
        } else {
            if (setMessages) {
                setMessages([])
            }
        }
    }, [messagesId, setMessages])

    return chatUser && userData ? (
        <div className='chat-box' style={{ display: `${chatVisible ? '' : ''}`}}>
            <div className="chat-user">
                <img src={chatUser.avatar} alt={t('talkive.chat.userAlt')} />
                <p>{chatUser.name} {Date.now() - chatUser.lastSeen <= 70000 ? <img src={assets.green_dot} alt="Nome" className="dot" /> : null}</p>
                <img src={assets.help_icon} className="help" alt={t('talkive.chat.help')} />
                <img onClick={() => setChatVisible && setChatVisible(false)} src={assets.arrow_icon} className="arrow" alt={t('talkive.chat.arrow')} />
            </div>

            <div className="chat-msg">
                {messages?.map((msg, index) => (
                    <div key={index} className={msg.sId === userData.id ? "s-msg" : "r-msg"}>
                        {msg.image ?
                            <img className="msg-img" src={msg.image} alt={t('talkive.chat.imageAlt')} /> : <p className="msg">{msg.text}</p>}
                        <div>
                            <img src={msg.sId === userData.id ? userData.avatar : chatUser.avatar} alt={t('talkive.chat.imageAlt')} />
                            <p>{convertTimestamp(msg.createdAt)}</p>
                        </div>
                    </div>
                ))}
            </div>

            <div className="chat-input">
                <input onChange={(e) => setInput(e.target.value)} value={input} type="text" placeholder={t('talkive.chat.sendMessagePlaceholder')} onKeyDown={handleKeyDown} />
                <input onChange={sendImage} type="file" id="image" accept="image/png, image/jpeg" hidden />
                <label htmlFor="image">
                    <img src={assets.gallery_icon} alt={t('talkive.chat.gallery')} />
                </label>
                <img onClick={sendMessage} src={assets.send_button} alt={t('talkive.chat.send')} />
            </div>
        </div>
    ) : (
        <div className={`chat-welcome ${chatVisible ? "" : "hidden"}`}>
            <img src={assets.logo_icon} alt="Logo" />
            <p>{t('talkive.chat.welcomeMessage')}</p>
        </div>
    )

}

export default ChatBox
