// client/src/components/Systems/Talkive/RightSideBar/RightSideBar.tsx
import { useContext, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import assets from "@/assets/talkive/ts/assets";
import { logout } from "@/api/talkive/config/firebase";
import { TalkiveContext } from "@/context/Talkive/TalkiveContext";
import './RightSideBar.sass'

const RightSideBar: React.FC = () => {
    const { t } = useTranslation()
    const talkiveContext = useContext(TalkiveContext)
    const chatUser = talkiveContext?.chatUser
    const messages = talkiveContext?.messages

    const [msgImages, setMsgImages] = useState<string[]>([])

    useEffect(() => {
        if (!messages || messages.length === 0) {
            setMsgImages([])
            return
        }

        const imageSet = new Set<string>()
        messages.forEach((msg) => {
            if (msg.image){
                imageSet.add(msg.image)
            }
        })
        setMsgImages(Array.from(imageSet))
    }, [messages])

    return chatUser ? (
        <div className="rs"> 
            <div className="rs-profile">
                <img src={chatUser.avatar} alt={t('talkive.profileAlt')} />
                <h3>{Date.now() - chatUser.lastSeen <= 70000 ? <img src={assets.green_dot} className="dot" alt={t('talkive.onlineAlt')} /> : null} {chatUser.name}</h3>
                <p>{chatUser.bio}</p>
            </div>
            <hr />
            <div className="rs-media">
                <p>{t('talkive.chat.media')}</p>
                <div>
                    {msgImages.map((url, index) => (
                        <img onClick={() => window.open(url)} key={index} src={url} alt={`${t('talkive.imageAlt')} ${index}`} />
                    ))}
                </div>
            </div>
            <button onClick={() => logout()}>{t('common.logout')}</button>
        </div>
    ) : (
        <div className="rs">
            <button onClick={() => logout()}>{t('common.logout')}</button>
        </div>
    )

}

export default RightSideBar

// client-angular/src/app/features/talkive/components/right-sidebar/right-sidebar.component.ts
import { Component, computed, inject } from '@angular/core';
import { TALKIVE_ASSETS } from '@/assets/talkive/ts/assets';
import { I18nService } from '@/app/core/services/i18n/i18n.service';
import { TalkiveStateService } from '@/app/core/services/state/talkive-state.service';
import { TalkiveService } from '@/app/core/services/talkive/talkive.service';

@Component({
  selector: 'app-talkive-right-sidebar',
  standalone: true,
  templateUrl: './right-sidebar.component.html',
})
export class TalkiveRightSidebarComponent {
  readonly assets = TALKIVE_ASSETS;
  readonly talkiveState = inject(TalkiveStateService);
  private readonly talkiveService = inject(TalkiveService);
  readonly i18n = inject(I18nService);

  readonly mediaImages = computed(() => {
    const images = new Set<string>();
    for (const msg of this.talkiveState.messages()) {
      if (msg.image) {
        images.add(msg.image);
      }
    }
    return Array.from(images);
  });

  isOnline(lastSeen: number): boolean {
    return Date.now() - lastSeen <= 70000;
  }

  async logout(): Promise<void> {
    await this.talkiveService.logout();
  }

  openImage(url: string): void {
    window.open(url, '_blank');
  }
}

<div class="rs">
  @if (talkiveState.chatUser(); as chatUser) {
    <div class="rs-profile">
      <img [src]="chatUser.avatar || assets.avatar_icon" [alt]="i18n.t('talkive.profileAlt')" />
      <h3>
        @if (isOnline(chatUser.lastSeen)) {
          <img [src]="assets.green_dot" class="dot" [alt]="i18n.t('talkive.onlineAlt')" />
        }
        {{ chatUser.name }}
      </h3>
      <p>{{ chatUser.bio }}</p>
    </div>
    <hr />
    <div class="rs-media">
      <p>{{ i18n.t('talkive.chat.media') }}</p>
      <div>
        @for (url of mediaImages(); track url) {
          <img [src]="url" [alt]="i18n.t('talkive.imageAlt')" (click)="openImage(url)" />
        }
      </div>
    </div>
  }
  <button type="button" (click)="logout()">{{ i18n.t('common.logout') }}</button>
</div>
