// client/src/components/Systems/Convene/UI/ErrorBlock/ErrorBlock.tsx
import Div from "@/components/Html/Div/Div"
import classes from "./ErrorBlock.module.css"

const ErrorBlock: React.FC<{title: string, message: string, errors?: any[]}> = ({title, message, errors}) => {
    return (
        <Div className={classes.errorBlock}>
            <Div className={classes.icon}>!</Div>
            <Div className="error-block-text">
                <h2 className={classes.h2}>{title}</h2>
                <p className={classes.p}>{message}</p>
                {errors && Object.values(errors).length > 0 && (
                    <ul>
                        {Object.values(errors).map((error, index) => (
                            <li key={index}>{error}</li>
                        ))}
                    </ul>
                )}
            </Div>
        </Div>
    )
}

export default ErrorBlock

// client-angular/src/app/features/convene/components/error-block/error-block.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-error-block',
  imports: [],
  templateUrl: './error-block.html',
  styleUrl: './error-block.css',
})
export class ErrorBlock {
  readonly title = input.required<string>();
  readonly message = input.required<string>();
  readonly errors = input<string[]>();
}
