// client-angular/src/app/shared/components/header-systems/header-systems.component.ts
import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/services/auth/auth.service';
import { I18nService } from '../../../core/services/i18n/i18n.service';

@Component({
  selector: 'app-header-systems',
  standalone: true,
  template: `
    <div class="mt-20 flex flex-col items-center px-4 text-center text-gray-800">
      <img
        src="/assets/png/header.png"
        [alt]="i18n.t('common.headerAlt')"
        class="mb-6 h-36 w-36 shrink-0 rounded-full object-cover"
      />

      <h1 class="mb-2 flex items-center gap-2 text-xl font-medium text-gray-800 sm:text-3xl">
        {{ i18n.t('home.hello', { name: userName() }) }}
        <img src="/assets/png/hand.png" class="aspect-square w-8" [alt]="i18n.t('common.robotAlt')" />
      </h1>

      <h2 class="mb-4 text-3xl font-semibold text-gray-800 sm:text-5xl">{{ i18n.t('home.welcome') }}</h2>
      <p class="mb-8 max-w-md text-gray-700">{{ i18n.t('home.startUsing') }}</p>

      @if (!isLoggedIn()) {
        <button
          type="button"
          (click)="goToLogin()"
          class="rounded-full border border-gray-500 px-8 py-2.5 text-gray-800 transition-all hover:bg-gray-100"
        >
          {{ i18n.t('home.letsGo') }}
        </button>
      } @else {
        <button
          type="button"
          (click)="goToSystems()"
          class="rounded-full border border-gray-500 px-8 py-2.5 text-gray-800 transition-all hover:bg-gray-100"
        >
          {{ i18n.t('home.systemsButton') }}
        </button>
      }
    </div>
  `,
})
export class HeaderSystemsComponent {
  private readonly authService = inject(AuthService);
  private readonly router = inject(Router);
  readonly i18n = inject(I18nService);

  userName(): string {
    return this.authService.userData()?.name ?? this.i18n.t('home.user');
  }

  isLoggedIn(): boolean {
    return this.authService.isLoggedIn();
  }

  goToLogin(): void {
    this.router.navigate(['/login']);
  }

  goToSystems(): void {
    this.router.navigate(['/systems']);
  }
}

// client/src/components/HeaderSystems/HeaderSystems.tsx
import { useContext } from "react";
import { useTranslation } from "react-i18next";
import { AppContext } from "@/context/AppContext";
import useNavigateSPA from "@/hooks/routes/useNavigateSPA";
import Image from "@/components/Html/Image/Image";
import Header2 from "@/components/Html/Header2/Header2";
import Div from "@/components/Html/Div/Div";
import Button from "@/components/Html/Button/Button"
import Paragraph from "@/components/Html/Paragraph/Paragraph";
import HeaderImg from "@/components/Html/HeaderImg/HeaderImg";
import header from "@/assets/png/header.png"
import hand from "@/assets/png/hand.png"

const HeaderSystems: React.FC = () => {

    const { t } = useTranslation()
    const navigate = useNavigateSPA()

    const context = useContext(AppContext)

    if (!context) {
        throw new Error(t('auth.appContextError'))
    }

    const { userData, isLoggedIn } = context
    const name = userData ? userData.name : t('home.user')

   return (
        <Div className="flex flex-col items-center mt-20 px-4 text-center text-gray-800">
            <Image src={header} alt={t('common.headerAlt')} className="w-36 h-36 rounded-full mb-6" />
            <HeaderImg className="flex items-center gap-2 text-xl sm:text-3xl font-medium mb-2 text-gray-800" text={t('home.hello', { name })}>
                <Image src={hand} className="w-8 aspect-square" alt={t('common.robotAlt')} />
            </HeaderImg>
            <Header2 className="text-3xl sm:text-5xl font-semibold mb-4 text-gray-800" text={t('home.welcome')} />
            <Paragraph className="mb-8 max-w-md text-gray-700" text={t('home.startUsing')} />
            {
                !isLoggedIn ?
                    <div onClick={() => navigate('/login')}>
                        <Button className="border border-gray-500 rounded-full px-8 py-2.5 hover:bg-gray-100 transition-all" text={t('home.letsGo')} />
                    </div>
                    : <div onClick={() => navigate('/systems')}>
                        <Button className="border border-gray-500 rounded-full px-8 py-2.5 hover:bg-gray-100 transition-all" text={t('home.systemsButton')} />
                    </div>
            }
        </Div>
   )
}

export default HeaderSystems
