// client-angular/src/app/features/crypto/components/line-chart/line-chart.ts
import { afterRenderEffect, Component, ElementRef, inject, input, viewChild } from '@angular/core';
import { IPricesCoinData } from '../../../../core/models';
import { I18nService } from '../../../../core/services/i18n/i18n.service';
import { ensureGoogleCharts } from '../../../../core/utils/google-charts.util';

@Component({
  selector: 'app-line-chart',
  imports: [],
  template: `<div #chartContainer class="chart-inner"></div>`,
  styleUrl: './line-chart.css',
})
export class LineChart {
  readonly historicalData = input.required<IPricesCoinData>();
  readonly refreshKey = input<string>('');
  readonly i18n = inject(I18nService);
  private readonly chartContainer = viewChild<ElementRef<HTMLDivElement>>('chartContainer');

  constructor() {
    afterRenderEffect(() => {
      const data = this.historicalData();
      const container = this.chartContainer()?.nativeElement;
      this.refreshKey();

      if (!container || !data?.prices?.length) {
        return;
      }

      ensureGoogleCharts(() => {
        requestAnimationFrame(() => this.draw(data, container));
      });
    });
  }

  private draw(historicalData: IPricesCoinData, container: HTMLElement): void {
    const visualization = window.google?.visualization;
    if (!visualization) {
      return;
    }

    container.innerHTML = '';

    const dataLabel = this.i18n.t('crypto.chartDataLabel');
    const priceLabel = this.i18n.t('crypto.chartPriceLabel');
    const tableData: Array<Array<string | number>> = [
      [dataLabel, priceLabel],
      ...historicalData.prices.map((item) => [
        new Date(item[0]).toLocaleDateString().slice(0, -5),
        item[1],
      ]),
    ];

    const width = container.clientWidth || container.offsetWidth || 600;
    const dataTable = visualization.arrayToDataTable(tableData);
    const chart = new visualization.LineChart(container);
    chart.draw(dataTable, {
      width,
      height: 250,
      title: this.i18n.t('crypto.chartTitle'),
      curveType: 'function',
      legend: { position: 'bottom' },
      chartArea: { width: '85%', height: '65%' },
      backgroundColor: 'transparent',
      colors: ['#7927ff'],
    });
  }
}

// client/src/components/Systems/Crypto/common/LineChart.tsx
import { useState, useEffect } from "react"
import { useTranslation } from "react-i18next"
import type { IPricesCoinData } from "@/interfaces/systems/crypto"
import Chart from "react-google-charts"

interface ILineChartProps {
    historicalData: IPricesCoinData;
}

const LineChart: React.FC<ILineChartProps> = ({ historicalData }) => {
    const { t } = useTranslation()
    const [data, setData] = useState<[string, string][]>([[t('crypto.chartDataLabel'), t('crypto.chartPriceLabel')]])

    useEffect(() => {
        const dataLabel = t('crypto.chartDataLabel')
        const priceLabel = t('crypto.chartPriceLabel')
        const dataCopy: [string, string | number][] = [[dataLabel, priceLabel]]
        if (historicalData.prices.length > 0) {
            historicalData.prices.map((item: any) => {
                dataCopy.push([`${new Date(item[0]).toLocaleDateString().slice(0, -5)}`, item[1]])
            })
        }
        setData(dataCopy as [string, string][])
    }, [historicalData, t])

    return (
        <Chart 
            chartType="LineChart"
            data={(data)}
            options={{
                title: t('crypto.chartTitle'),
                curveType: "function",
                legend: { position: "bottom" },
            }}
        />
    )
}
export default LineChart
